name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 3 * * *' # Runs every day at 3am

jobs:
  build_package:
    name: Build registry
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Generator
        id: cache-generator
        uses: actions/cache@v2
        with:
          path: swift-package-collection-generator
          key: ${{ runner.os }}-generator

      - name: Setup Generator
        if: steps.cache-generator.outputs.cache-hit != 'true'
        run: |
          git clone -b 5.5 https://github.com/apple/swift-package-collection-generator
          cd swift-package-collection-generator
          swift build --configuration release
          cd ../

      - name: Generate Collection
        run: |
          cd swift-package-collection-generator
          ./.build/release/package-collection-generate ../packages.json ../build/collection.json
          cd ../

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
